[package]
name = "wgpu_boids"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
bytemuck = { version = "1.16", features = ["derive"] }
wgpu = "22.0"
pollster = "0.3"
anyhow = "1.0"
env_logger = "0.10"
log = "0.4"
rand = "0.9.0"
